import type {
  Indent,
  IndentItem,
  IndentAttachment,
  IndentTimelineEvent,
  IndentComment,
} from "@/types";
import { formatDate, formatINR } from "@/utils/format";

// Material category lookup dictionary
const categoryLookup: Record<string, string> = {
  cement: "Cement",
  steel: "Steel & Rebars",
  tmt: "Steel & Rebars",
  brick: "Masonry",
  block: "Masonry",
  sand: "Aggregates",
  aggregate: "Aggregates",
  tile: "Finishes",
  paint: "Finishes & Paint",
  pipe: "Plumbing & Drainage",
  cable: "Electrical & Conduits",
  concrete: "RMC Concrete",
  chemical: "Construction Chemicals",
  screed: "Flooring",
  dock: "MEP Equipment",
};

export function getCategoryForItem(itemName: string): string {
  const lower = itemName.toLowerCase();
  for (const [k, v] of Object.entries(categoryLookup)) {
    if (lower.includes(k)) return v;
  }
  return "General Civil";
}

export function getTimelineForStatus(
  indent: Indent,
  status: Indent["status"],
  remarks?: string,
): IndentTimelineEvent[] {
  const baseDate = formatDate(indent.date);
  const base: IndentTimelineEvent[] = [
    {
      id: `tl-${indent.id}-1`,
      title: "Indent Created",
      description: `Indent ${indent.indentNo} generated by ${indent.requestedBy} for ${indent.department} department.`,
      timestamp: `${baseDate} 09:30 AM`,
      user: indent.requestedBy,
      type: "created",
    },
    {
      id: `tl-${indent.id}-2`,
      title: "Submitted for Approval",
      description: `Forwarded to Level 1 (Project Manager) for technical validation.`,
      timestamp: `${baseDate} 10:15 AM`,
      user: indent.requestedBy,
      type: "submitted",
    },
    {
      id: `tl-${indent.id}-3`,
      title: "Site Store Verification",
      description: "Store inventory audited; buffer stock and consumption confirmed.",
      timestamp: `${baseDate} 02:40 PM`,
      user: "Site Store Keeper",
      type: "system",
    },
  ];

  if (status === "Draft") {
    return base.slice(0, 1);
  }

  if (status === "Pending") {
    base.push({
      id: `tl-${indent.id}-4`,
      title: "Approval Pending",
      description: `Currently awaiting review at ${indent.level || "Level 1 — Project Manager"}.`,
      timestamp: `${baseDate} 03:00 PM`,
      user: indent.level || "Project Manager",
      type: "system",
    });
    return base;
  }

  if (status === "Approved") {
    base.push(
      {
        id: `tl-${indent.id}-4`,
        title: "Approval Pending",
        description: "Awaiting multi-tier technical and commercial authorization.",
        timestamp: `${baseDate} 03:00 PM`,
        user: "Approval Workflow Engine",
        type: "system",
      },
      {
        id: `tl-${indent.id}-5`,
        title: "Project Manager Approval",
        description:
          remarks || "Technical specifications, quantities, and schedule alignment approved.",
        timestamp: `${baseDate} 04:30 PM`,
        user: "Rajesh Sharma (PM)",
        type: "approved",
      },
      {
        id: `tl-${indent.id}-6`,
        title: "Purchase Head Approval",
        description: "Budget clearance and purchase strategy sanctioned.",
        timestamp: `${baseDate} 05:45 PM`,
        user: "Amitav Roy (Purchase Head)",
        type: "approved",
      },
      {
        id: `tl-${indent.id}-7`,
        title: "Finance Approval",
        description: "Financial allocation and credit terms cleared.",
        timestamp: `${baseDate} 06:00 PM`,
        user: "Finance Controller",
        type: "approved",
      },
      {
        id: `tl-${indent.id}-8`,
        title: "Final Approval",
        description: "Final procurement approval signed off.",
        timestamp: `${baseDate} 06:15 PM`,
        user: "Central Procurement Cell",
        type: "approved",
      },
      {
        id: `tl-${indent.id}-9`,
        title: "Indent Approved",
        description: `Indent released for vendor Enquiry / RFQ generation. Total value: ${formatINR(indent.value, { compact: true })}.`,
        timestamp: `${baseDate} 06:20 PM`,
        user: "Procurement Cell",
        type: "approved",
      },
    );
    return base;
  }

  if (status === "Rejected") {
    base.push(
      {
        id: `tl-${indent.id}-4`,
        title: "Approval Pending",
        description: "Awaiting review.",
        timestamp: `${baseDate} 03:00 PM`,
        user: "Approval Workflow Engine",
        type: "system",
      },
      {
        id: `tl-${indent.id}-5`,
        title: "Indent Rejected",
        description:
          remarks || "Rejected during review: Budget variance exceeds quarterly material ceiling.",
        timestamp: `${baseDate} 04:20 PM`,
        user: "Rajesh Sharma (PM)",
        type: "rejected",
      },
    );
    return base;
  }

  if (status === "Returned" || status === "Sent Back") {
    base.push(
      {
        id: `tl-${indent.id}-4`,
        title: "Approval Pending",
        description: "Awaiting review.",
        timestamp: `${baseDate} 03:00 PM`,
        user: "Approval Workflow Engine",
        type: "system",
      },
      {
        id: `tl-${indent.id}-5`,
        title: "Returned for Clarification",
        description:
          remarks ||
          "Please verify whether existing site inventory can cover next 10 days of casting.",
        timestamp: `${baseDate} 03:50 PM`,
        user: "Amitav Roy (Purchase Head)",
        type: "returned",
      },
    );
    return base;
  }

  return base;
}

/**
 * Ensures an Indent record has complete item specifications,
 * attachments, activity timeline, and comments.
 */
export function enrichIndentDetails(indent: Indent): Indent {
  // 1. Enrich Items with all 10 required fields
  const enrichedItems: IndentItem[] = indent.items.map((it, idx) => {
    const category = it.category || getCategoryForItem(it.item);
    const itemCode =
      it.itemCode ||
      `MAT-${String(100 + ((idx * 37 + indent.indentNo.charCodeAt(indent.indentNo.length - 1)) % 899))}`;
    const itemDescription =
      it.itemDescription ||
      `${it.item} - Site grade specification confirming to IS standard requirements for ${indent.department.toLowerCase()} works.`;
    const indentQty = it.indentQty ?? it.quantity;
    const requestedQty = it.requestedQty ?? Math.round(indentQty * 1.08);
    const availableStock = it.availableStock ?? Math.max(0, Math.round(indentQty * 0.12));
    const amount = it.amount ?? indentQty * it.rate;
    const remarks =
      it.remarks && it.remarks.trim()
        ? it.remarks
        : `Approved BOQ item. Delivery at ${indent.site} store.`;

    return {
      ...it,
      itemCode,
      itemDescription,
      category,
      requestedQty,
      availableStock,
      indentQty,
      rate: it.rate,
      amount,
      remarks,
    };
  });

  // Recalculate total value and count
  const calculatedValue = enrichedItems.reduce(
    (s, it) => s + (it.amount ?? it.quantity * it.rate),
    0,
  );

  // 2. Default Attachments if none provided
  const attachments: IndentAttachment[] = indent.attachments ?? [
    {
      id: `att-${indent.id}-1`,
      fileName: `Site_Indent_Requisition_${indent.indentNo.replace(/\//g, "-")}.pdf`,
      fileType: "PDF",
      fileSize: "1.4 MB",
      uploadedBy: indent.requestedBy,
      uploadedDate: indent.date,
    },
    {
      id: `att-${indent.id}-2`,
      fileName: `BOQ_Material_Variance_Extract_${indent.project.substring(0, 10).replace(/\s+/g, "_")}.xlsx`,
      fileType: "XLSX",
      fileSize: "420 KB",
      uploadedBy: "Planning Engineer",
      uploadedDate: indent.date,
    },
    {
      id: `att-${indent.id}-3`,
      fileName: "Store_Stock_Verification_Slip.pdf",
      fileType: "PDF",
      fileSize: "890 KB",
      uploadedBy: "Site Store Incharge",
      uploadedDate: indent.date,
    },
  ];

  // 3. Activity Timeline
  // Ensure "Approval Pending" is never present AFTER "Indent Approved"
  const rawTimeline =
    indent.timeline && indent.timeline.length > 0
      ? indent.timeline
      : getTimelineForStatus(indent, indent.status);

  // Re-verify ordering so that "Indent Approved" is always the final terminal state
  const timeline: IndentTimelineEvent[] = [...rawTimeline];
  const approvedIdx = timeline.findIndex((t) => t.title === "Indent Approved");
  if (approvedIdx >= 0) {
    // Remove any trailing "Approval Pending" that might have been erroneously added after approval
    const sanitized = timeline.filter(
      (t, i) => !(t.title === "Approval Pending" && i > approvedIdx),
    );
    timeline.length = 0;
    timeline.push(...sanitized);
  }

  // 4. Default Comments
  const comments: IndentComment[] = indent.comments ?? [
    {
      id: `cm-${indent.id}-1`,
      author: indent.requestedBy,
      role: "Site Incharge",
      timestamp: `${formatDate(indent.date)} 09:35 AM`,
      text: `Required urgently on site by ${formatDate(indent.requiredDate)} for upcoming concrete pouring schedule. Please prioritize delivery.`,
    },
  ];

  if (indent.status === "Approved") {
    comments.push({
      id: `cm-${indent.id}-2`,
      author: "Rajesh Sharma",
      role: "Project Manager",
      timestamp: `${formatDate(indent.date)} 04:32 PM`,
      text: "Approved as per BOQ provision. Procurement team to float RFQ to empaneled tier-1 vendors.",
    });
  } else if (indent.status === "Returned" || indent.status === "Sent Back") {
    comments.push({
      id: `cm-${indent.id}-2`,
      author: "Amitav Roy",
      role: "Purchase Head",
      timestamp: `${formatDate(indent.date)} 03:52 PM`,
      text: "Kindly verify physical stock in warehouse before we issue purchase order.",
    });
  }

  return {
    ...indent,
    value: calculatedValue || indent.value,
    itemCount: enrichedItems.length,
    items: enrichedItems,
    attachments,
    timeline,
    comments,
  };
}
